### ISSUE TITLE
Carrinho abandonado de 1 cliente gera erro

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus-bot/app-evendas#69]
**Descreva o bug**
De 1 cliente está dando resposta 200, mas nao recebem, o que foi falado é que mesmo dando 200, pode dar uma mensagem informando que algo aconteceu, por isso colocando ai o data pra buscar o que tiver de resposta disso

**Comment by leomp12** [comment]
> mesmo dando 200, pode dar uma mensagem informando que algo aconteceu

<div class="_3xYY6QR2VuQXUgyDTl0hyu _3zM-WhDmCDfr3adQw5Zj3I" data-sticker="false"><div><div><video style="width: 100%; height: 100%;" alt="Tired Amazon Studios GIF by Prime Video Comedy" src="https://media4.giphy.com/media/oBcmNdG4B7f0YdDVTk/giphy.mp4?cid=ecf05e47mygmswrb381q27ayt6f7ju5h6ksvmzbibuxbdyj7&amp;rid=giphy.mp4&amp;ct=g" poster="https://media4.giphy.com/media/oBcmNdG4B7f0YdDVTk/giphy_s.gif?cid=ecf05e47mygmswrb381q27ayt6f7ju5h6ksvmzbibuxbdyj7&amp;rid=giphy_s.gif&amp;ct=g" autoplay="" loop="" playsinline=""></video><img src="https://media4.giphy.com/media/oBcmNdG4B7f0YdDVTk/giphy.gif?cid=ecf05e47mygmswrb381q27ayt6f7ju5h6ksvmzbibuxbdyj7&amp;rid=giphy.gif&amp;ct=g" alt="Tired Amazon Studios GIF by Prime Video Comedy" style="width: 100%; height: 100%; opacity: 0;"></div></div></div>
